### ISSUE TITLE
License discussion

### ISSUE THREAD

**Issue by Calinou** [froala/design-blocks#26]
Hello,

I've noticed that [this project uses a custom license](https://github.com/froala/design-blocks/blob/master/LICENSE).

Unfortunately, not only custom licenses can be a barrier to adoption in some places (such as corporate environments), but this particular license also doesn't follow the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html) and the [Open Source Definition](https://opensource.org/osd), since it restricts the permitted use cases (among other issues).

It could also be argued that [commercial use is not necessarily unethical](https://freedomdefined.org/Licenses/NC).

Would you please consider switching to an [open source license](https://choosealicense.com/)?

**Comment by stefanneculai** [comment]
We've put the Froala Design Blocks product free in order to encourage the worldwide development of collaborative web design projects and to provide a free and open framework in which web design may be shared and improved in partnership with others. Indeed, we put there some limitations which we believe as being common sense:
 - do not use for website or app generators;
 - do not use to create templates, themes, and plugins for sale.

We're going to keep them for the moment, however, we might reconsider it at a further point.

Except for these 2 limitations, all other license terms should be compatible with Open Source definitions and we believe that both devs and designers could make good use of it under the current terms in order to create amazing products faster by having a solid good looking design.
