### ISSUE TITLE
Create PSD files for each design block

### ISSUE THREAD

**Issue by stefanneculai** [froala/design-blocks#34]

**Comment by stefanneculai** [comment]
@djstojadin that would be amazing. Looking forward to seeing them.

**Comment by stephaniepurvis** [comment]
I am interested in helping on this too. I was thinking about using the resource here to create artboards for each breakpoint: https://hackerthemes.com/bootstrap-4-grid-psd/

@djstojadin Let me know if you'd like me to help and what section you'd like me to start on.

**Comment by djstojadin** [comment]
In general this is my idea and how it is looks like. Take a look and let me know what do you think. 
[boilerplate.zip](https://github.com/froala/design-blocks/files/1409793/boilerplate.zip)

**Comment by stefanneculai** [comment]
@djstojadin it looks pretty good. @stephaniepurvis looking to hear your thoughts too.

**Comment by stephaniepurvis** [comment]
@djstojadin and @stefanneculai I think the psd looks great!

**Comment by djstojadin** [comment]
I started with call-to-action blocks. Files are named t1, t2, t3 etc... **t** is shorthand for **type** starting from top to bottom according to website. 

Check examples for first 4 call to action design blocks. 
[db-call-to-action-1-4.zip](https://github.com/froala/design-blocks/files/1414316/db-call-to-action-1-4.zip)

@stefanneculai  Let me know where do you want to store files while I am working?

**Comment by stefanneculai** [comment]
@djstojadin they look good, but it appears there are no guides? @dianaprajescu do you have any input on this?

**Comment by djstojadin** [comment]
@stefanneculai Guides are removed, but I can create them again that is not problem.

**Comment by dianaprajescu** [comment]
Indeed, I think we should keep the grid in the PSD files. It will help if we need to make any changes later. Also, if we ever get to created PSD files in advance and then write the code for them, the guides will be helpful and we should have old and new PSD files built in the same manner for consistency.

@djstojadin the call to action PSD files look good. One note though: while the breakpoints in the boilerplate.psd file are correct, I think there has been a confusion in the call to actions you created. In the boilerplate file, the @xs is not represented because the container width is set to auto. So the breakpoints are for @sm, @md, @lg and @xl. @xl is new in Bootstrap 4: https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by stefanneculai** [comment]
Thanks to @creativetimofficial we have them now: https://github.com/froala/design-blocks/blob/dev/assets/psds/psd-pages.zip
