### ISSUE TITLE
[Suggestion] Demos on the site

### ISSUE THREAD

**Issue by sajadghawami** [froala/design-blocks#62]
Hey there,

How come all the demos on the site are images and not the actual design-blocks?

**Comment by dianaprajescu** [comment]
Hi @sajadghawami, our website was meant to be a sneak-peak of the design blocks where you can see as many blocks as possible to make an idea about the project. If you download the project, you'll be able to see the actual design blocks.

For the actual design blocks on our website, we would have needed to use the entire width for each block, instead of showing 3 on a row like we have now. We didn't want to create a list that is too long to scroll through.

On the Froala website, we're thinking of showing the actual design block when someone clicks on a design block.

**Comment by sajadghawami** [comment]
Sounds good! Thanks for the quick reply :)
